# Render.com Configuration for Backend Deployment
# Place this file in the root directory alongside vercel.json

services:
  - type: web
    name: iwanyu-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: iwanyu-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FLUTTERWAVE_PUBLIC_KEY
        sync: false
      - key: FLUTTERWAVE_SECRET_KEY
        sync: false
      - key: FLUTTERWAVE_WEBHOOK_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://iwanyu.vercel.app

databases:
  - name: iwanyu-db
    plan: starter
    databaseName: iwanyu_production
    user: iwanyu_user
