services:
  - type: web
    name: iwanyu-backend
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: iwanyu-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-vercel-app.vercel.app
  
  - type: pserv
    name: iwanyu-db
    env: postgres
    plan: free
    region: oregon
